### ISSUE TITLE
Add parent theme CSS support to the build tool

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla-cli#41]
When I'm building a theme I want to be able to access the scss from its parent theme(s). If I add my own scss file then it should be used instead. Here is my basic idea.

Parent theme: style.css

```scss
@import "theme/style";
```

Child theme: style.css

```scss
@import "variables";
@import "theme/style";
```

The child theme overrides the parent theme completely, but we make the files that are overridden very light.

I can see an issue where the child may accidentally override a parent theme's file when it shouldn't. My proposed solution involves a convention where parent themes but their SCSS into an implementation folder where child themes always add to the root. In the example above the parent theme would have a file called **theme/variables** for default variables and the child theme overrides it in just **variables**. Let's discuss.

**Comment by slafleche** [comment]
So the child themes variables need to be included first. The variable overwrites will get white listed with the "!default" property. 

To avoid any conflicts with the parent theme, why not compile all the child theme's partials into one file and include that one file as a partial. That way, you could have partials that are called the same without conflict.

**Comment by tburry** [comment]
From our discussion, something like the following include process will be used for SCSS compilation:

```
/parent/.../_vendor.scss
 /child/.../_variables.scss
/parent/.../_variable-defaults.scss
/parent/.../_base.scss
/parent/.../_vendor-overrides.scss
 /child/.../_custom.scss
```

The parent theme itself will compile just as a normal theme with something like the following style.scss:

```scss
@import "vendor.scss";
@import "variables.scss"; // blank placeholder file
@import "variable-defaults.scss";
@import "base.scss";
@import "vendor-overrides";
@import "custom"; // blank placeholder file
```

To support theme inheritance chains, the child themes will all be grouped together and their imports will look like the following:

```
/grand-child/.../_variables.scss
      /child/.../_variables.scss

      /child/.../_custom.scss
/grand-child/.../_custom.scss
```

**Comment by Charrondev** [comment]
## Implementation Plan
- [ ] Pull addon manager related functionality out into a Trait so that it can be used in the NodeCommandBase
- [ ] Allow common parameters to be re-used between commands
- [ ] Allow passing of entry points from PHP to JS
- [ ] Dynamically generate a build able entry point.
- [ ] Implement Validation of entry points (Should have placeholders/syntax for where child theme items get inserted.)
